### ISSUE TITLE
Which firmware is the default?

### ISSUE THREAD

**Issue by awickert** [NorthernWidget-Skunkworks/Project-Symbiont-LiDAR#7]
There are three currently. Could we either remove deprecated ones or create a "FirmwareTests" folder or a "tests" subfolder or something like this to distinguish?

**Comment by bschulz1701** [comment]
Sorry for the naming confusion, **`LiDAR_InterfaceDemo.ino`** should be the full functional firmware. `LiDAR_Accelerometer_InterfaceDemo.ino` does not have full control functionality for the LiDAR Lite or the hall effect sensor, and `HallEffect_Tester.ino` is simply a demo script to test magnet strength and area of effect most easily

**Comment by awickert** [comment]
* Renamed `LiDAR_InterfaceDemo.ino` to `LiDAR_Interface.ino`
* Moved the others to a subfolder with the notes provided here.
