### ISSUE TITLE
Which software should we use to create the library?

### ISSUE THREAD

**Issue by awickert** [NorthernWidget-Skunkworks/Project-Symbiont-LiDAR#9]
https://github.com/NorthernWidget-Skunkworks/Project-Symbiont-LiDAR/blob/master/Software/LiDARLite_I2CParse/LiDARLite_I2CParse.ino looks to be the most recent and the closest to the standard that @bschulz1701 has set for our other libraries. Does this one seem correct?

**Comment by bschulz1701** [comment]
I believe this is the correct demo script

**Comment by awickert** [comment]
Thank you! `README.md` added indicating this.
